### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by TalSchuster** [julienr/vim-cellmode#24]
python 3

ubuntu
python 3.6.5
ipython 6.4.0
vim 7.4

Getting this error on C-g:
```
Error detected while processing :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 94, in run_tmux_python_cell
vim.error: Vim(python):Traceback (most recent call last):
Press ENTER or type command to continue
```

and this error when selecting lines and C+c:
```
Error detected while processing :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 62, in run_tmux_python_chunk
  File "<string>", line 30, in send_to_tmux
  File "<string>", line 5, in set_register
vim.error: Vim(let):E354: Invalid register name: '+'
Press ENTER or type command to continue
```

**Comment by julienr** [comment]
Looks like the script is using some unsupported features. It's strange because I have used this script at work on Ubuntu 16.04.

Are you on Ubuntu 16.04 ? This is with vim from the ubuntu packages ?

**Comment by TalSchuster** [comment]
Thanks for your help it is with Ubuntu 16.04:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

and its on a sever but I think that vim is from ubuntu packages
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     +tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
-clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      +lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm
```

Tried also locally from a mac and couldn't make it work

**Comment by julienr** [comment]
I have never seen that error and I'm regularly running this on both OSX and Ubuntu 16.04... I'm not quite sure what else I can do to help. Could it be another plugin messing with the register names ?

The only thing strange I see in the error messages is that the function is called `run_tmux_python_cell`, but in the code, it's actually `RunTmuxPythonCell`. I'm not sure if this is normal vim behavior or not.

Maybe one thing to try would be to test with an empty .vimrc (well, just this plugin), to check if it's a configuration issue.

I'm sorry I cannot be more helpful, but I have really no idea what's going on.
